name: Deploy to Azure Wep App

on:
  workflow_dispatch

env:
  AZURE_WEBAPP_NAME: DocumentsVault    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.\AZ204-DocumentVault\'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '7.0.x'             # set this to the dot net version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags

    # Run dotnet build and publish
    - name: dotnet build and publish
      run: |
          dotnet restore ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          dotnet build --configuration Release ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          dotnet publish ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
          
    # Deploy to Azure Web apps
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
